WIP Proposal for People Import Helper
opensupporter/osdi-docs pull request #335
Opened 2019-04-12 22:08 UTC by joshco

Based on the need of apps like Spoke or CRMs to have people imported in batches vs single API call per person, this is a proposal for a new helper osdi:people_import_helper.  It's been prototyped as a Spoke contacts API with links below.

This helper allows a client to essentially batch up a set of person_signup_helper object into an array and upload all at once. By wrapping the signup objects, rather than an array of people, this allows the helper action functions like add_tags et al to be invoked individually for each person in the array.

The implementation could use the same endpoint for the osdi:person_signup_helper and osdi:people_import_helper but parse the body and behave accordingly.  This allows a client to discover if it can do a batched import, or if it must go through the pain of individually uploading each person.

As for the response to the batch helper, I think Larry has the right idea.  The response should be status information on errors/validation failures.  We currently have osdi:error defined which could be a good way to represent this, and the data Larry's code is returning.  I've added a new attribute within osdi:errors to accommodate batch requests.

I've added some stats attributes to the response object as a stake in the ground, but am interested in hearing what others think about what's necessary.  Please let me know

LINKS
Larry, @lperson original PR:  https://github.com/MoveOnOrg/Spoke/pull/967
Josh's OSDI-ifying branch:  https://github.com/MoveOnOrg/Spoke/compare/main...joshco:osdi_contacts
GHP Formatted spec for person_import_helper:  https://joshco.github.io/osdi-docs/people_import_helper.html

2019-07-12 14:45 UTC, mlncn commented
Technically seems like a great idea.

Minor question on the markdown formatting of the documentation:

Sometimes JSON is introduced with four backticks instead of three:

<pre>
 ````json 
</pre>

and likewise the use of four backticks around `osdi:people_import_helper` seems maybe more than intended; what does that do that one backtick doesn't do?

Thanks for this work!

2019-07-15 14:03 UTC, joshco commented
Thanks for the feedback and the eagle eye on the back-ticks.  That's my error.
At some point my brain must have transposed the 3 and the 4 in the markdown definition for code blocks.
> "Blocks of code are either fenced by lines with three back-ticks ```, or are indented with four spaces. "

As far as I know, there's no other benefit to the 4th back-tick, except perhaps the visual order of even / balanced back-ticks.

If you have the time, please put together a pull request changing them to 3 back-ticks,, so you'll be recognized for your contribution.

If not, LMK, I'll handle it.

2019-07-22 11:50 UTC, mlncn commented on errors.md
> +When a Batch Request response includes ````osdi:error```` status information, the response code in the parent request should reflect the status of the batch operation itself, such as the import opera
Remove excess tick marks

2019-07-22 11:58 UTC, mlncn requested changes
Here's the changes to the markdown code formatting (number of tickmarks made standard, only).

GitHub claims there's a way now for these comments to be accepted as commits!

2019-07-22 11:58 UTC, mlncn commented on errors.md
> +The sub-request error status is contained within an array with attribute name ````batch_errors````.  The sub-request array may omit status on successful sub-requests and only contain errors.
```suggestion
The sub-request error status is contained within an array with attribute name `batch_errors`.  The sub-request array may omit status on successful sub-requests and only contain errors.
```

2019-07-22 11:58 UTC, mlncn commented on errors.md
> +A batch of people is uploaded via the ````osdi:people_import_helper````.  The overall upload succeeds, but there are two errors that are reported.
```suggestion
A batch of people is uploaded via the `osdi:people_import_helper`.  The overall upload succeeds, but there are two errors that are reported.
```

2019-07-22 11:58 UTC, mlncn commented on errors.md
> +The first is an invalid tag in the ````add_tags```` helper action function, but the import of the person itself succeeds.
```suggestion
The first is an invalid tag in the `add_tags` helper action function, but the import of the person itself succeeds.
```

2019-07-22 11:58 UTC, mlncn commented on people_import_helper.md
> +If errors occurred on individual signups, the response should contain an ````osdi:error```` object for batch requests indicating the individual status information.
```suggestion
If errors occurred on individual signups, the response should contain an `osdi:error` object for batch requests indicating the individual status information.
```

2019-07-22 11:58 UTC, mlncn commented on people_import_helper.md
> +The link relation label for the People import helper is ```osdi:people_import_helper```.
```suggestion
The link relation label for the People import helper is `osdi:people_import_helper`.
```

2019-07-22 11:58 UTC, mlncn commented on people_import_helper.md
> +````json
```suggestion
```json
```

2019-07-22 11:58 UTC, mlncn commented on people_import_helper.md
> +````
```suggestion
```
```

2019-07-22 11:58 UTC, mlncn commented on people_import_helper.md
> +````json
```suggestion
```json
```

2019-07-22 11:58 UTC, mlncn commented on people_import_helper.md
> +````
```suggestion
```
```

2019-07-22 11:58 UTC, mlncn commented on errors.md
> +In order to report errors for each sub-request, the ````batch_errors```` attribute is included, which is an array of ````osdi:error```` objects defined here.
```suggestion
In order to report errors for each sub-request, the `batch_errors` attribute is included, which is an array of `osdi:error` objects defined here.
```

2019-07-22 11:58 UTC, mlncn commented on errors.md
> +Batch requests are a collection of similar requests sent to the server in one OSDI call.  For example, the ````osdi:people_import_helper```` request includes an array of signups, where each array ite
```suggestion
Batch requests are a collection of similar requests sent to the server in one OSDI call.  For example, the `osdi:people_import_helper` request includes an array of signups, where each array item is what would normally be in a single request to `osdi:person_signup_helper`.
```

2020-01-15 15:39 UTC, closed without merging